* Password Reset Dashboard

Based on code from an engagement, where a .NET endpoint was used to 
allow a semi-trusted third party perform active directory password 
resets for user accounts. 

The accounts the remote vendor were permitted to reset were incremental
numbers and prefixed with a 'u' (eg 'u00001', 'u00002' etc). 

One cool vulnerability type I didn't include is [[https://andrewlock.net/preventing-mass-assignment-or-over-posting-in-asp-net-core/][Overposting]], you should
still read up on it, because it's a damn cool vulnerability class and 
exists in at least MVC.NET w/ similar vulns in other languages too!

* Instructions
Clone repo locally, review files containing the string ~ReviewMe~
understand code, read doco, attempt exploits.

This demonstration has  AD/Local user account reset disabled, but when 
uncommented actually resets Local user account passwords, AD requires 
additional configuration.

The demonstrated code contains _multiple_ vulnerabilities. At least
four. Go for the throat, then focus on the silly ones you're supposed
to care about during pentests. 

You can use the account ~Pentest@sectalks.org~ with the password 
~Password1!~ to authenticate. 

** Bonus Points
Fix discovered vulnerabilities and verify fixes work!

* Local Setup
(Hopefully) The csproj works. If not be sad.

